# Site settings
title: From Dusk Till Dawn
email: your_email@example.com # Optional: use your actual email or remove if not used
description: >- # Add your project description here
  An interactive data visualization project exploring crime trends in San Francisco.

# GitHub Pages Project Site Settings (VERY IMPORTANT)
# These tell Jekyll how to construct URLs for your site when deployed.
url: "https://ThomasRoennebek.github.io" # Your GitHub username's Pages domain
baseurl: "/fromdusktilldawn.github.io"   # The name of THIS repository, preceded by a slash

# Theme and Skin
minimal_mistakes_skin: contrast # Or your preferred skin
remote_theme: mmistakes/minimal-mistakes

# Site Features
search: false # Disable search icon

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks and Pagination (Optional - remove if not needed for a single-page site)
# permalink: /:categories/:title/ # Default for posts, not usually for single page sites
# paginate: 5
# paginate_path: /page:num/

timezone: Europe/Copenhagen # Correct for your location

# Defaults for different content types
defaults:
  - scope:
      path: "" # Apply to all files not otherwise specified (e.g., your root index.md if it's not in _pages)
      type: pages
    values:
      layout: single # Assumes your index.md uses this layout
      author_profile: false
      classes: wide # Makes content area wider
  - scope:
      path: "_pages" # If you have other pages inside a _pages folder
      type: pages
    values:
      layout: single
      author_profile: false
      classes: wide
  # Remove 'posts' scope if you are not using blog posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: false
  #     read_time: false
  #     comments: false
  #     share: false
  #     related: false
  #     classes: wide

# Build settings: Folders and files Jekyll should process and copy to _site
include:
  - _pages       # If your index.md or other pages are here
  - assets/css   # For your main.scss
  - assets/images  # CRITICAL: Since your HTML plots are here
  - assets/js    # If you have custom JavaScript files
  - _data        # If you use Jekyll data files
  # - assets/interactive # REMOVE THIS if you are not using an "interactive" folder

# Files and folders Jekyll should ignore
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/ # Covers common Bundler paths like vendor/bundle, vendor/cache, etc.
  - README.md # Usually not needed in the final site output
  # Add any other files or folders you want Jekyll to ignore like .jekyll-cache, .sass-cache

plugins:
  # - jekyll-paginate # Remove if not using pagination settings above
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed # Usually for blogs, can be removed if not needed
  - jemoji
  - jekyll-include-cache

# Author info (Optional, remove if author_profile is false everywhere and not used)
author:
  name   : "Group 47"
  bio    : "Social data analysis and visualization"
  links: []

# Footer links (Optional)
footer:
  links: []

# Collections (Remove if not using custom Jekyll collections)
# collections:
#   stories:
#     output: true
#     permalink: /:collection/:name/